<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;

class Resource extends Model
{
    protected $fillable = [
        'details',
        'url',
        'article_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // escucha que cuando se elimina un recurso que lo haga directamente en el servidor
        static::deleting(function ($resource) {
            Storage::disk('public')->delete($resource->url);
        });
    }

    public function article(): BelongsTo
    {
        return $this->belongsTo(Article::class);
    }
}
